### ISSUE TITLE
Error on `ds login` 

### ISSUE THREAD

**Issue by flxwu** [entropic-dev/entropic#101]
After running `curl -sSL https://www.entropic.dev/install.sh | bash`, trying `ds login` gives the error below:
```
Error: /Users/flxwu/.entropicrc
    at load (/Users/flxwu/.nvm/versions/node/v8.11.4/lib/node_modules/ds/lib/config.js:21:11)
    at main (/Users/flxwu/.nvm/versions/node/v8.11.4/lib/node_modules/ds/lib/main.js:19:26)
    at Object.<anonymous> (/Users/flxwu/.nvm/versions/node/v8.11.4/lib/node_modules/ds/lib/main.js:49:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
```

**Comment by itsananderson** [comment]
I think that's because you're using Node 8 and [config.js relies on fs.promises](https://github.com/entropic-dev/entropic/blob/d3dbbb6795b3222130ffe31b08faedde3ab70176/cli/lib/config.js#L5) which was first added as an experimental API in Node 10 and a stable API in Node 11

**Comment by chrisdickinson** [comment]
Great catch @itsananderson – that's totally it. I'll add "minimum requirements" section to the README.

**Comment by chrisdickinson** [comment]
Added! I'm going to close this issue and open a pinned issue re: the login issue on node < 12. Thanks for the bug report, @flxwu!
