### ISSUE TITLE
Failed to login on new instance

### ISSUE THREAD

**Issue by toddself** [entropic-dev/entropic#127]
Got 

```
registry_1  | ⚠️ Response from registry/handlers/* > 500ms fetching "GET /www/login/providers/github/callback?code=2903b914d5428f6e950c&state=0.6057451335630384".
registry_1  |  - (Tune timeout using DEV_LATENCY_WARNING_MS env variable.)
registry_1  | error: database "entropic_development" does not exist
registry_1  |     at Connection.parseE (/services/registry/node_modules/pg/lib/connection.js:553:11)
registry_1  |     at Connection.parseMessage (/services/registry/node_modules/pg/lib/connection.js:378:19)
registry_1  |     at Socket.<anonymous> (/services/registry/node_modules/pg/lib/connection.js:119:22)
registry_1  |     at Socket.emit (events.js:200:13)
registry_1  |     at addChunk (_stream_readable.js:290:12)
registry_1  |     at readableAddChunk (_stream_readable.js:271:11)
registry_1  |     at Socket.Readable.push (_stream_readable.js:226:10)
registry_1  |     at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
registry_1  | From previous event:
registry_1  |     at materialize (/services/registry/node_modules/ormnomnom/lib/queryset.js:404:19)
registry_1  |     at QuerySet.createStream (/services/registry/node_modules/ormnomnom/lib/queryset.js:233:5)
registry_1  |     at /services/registry/node_modules/ormnomnom/lib/queryset.js:261:24
registry_1  | From previous event:
registry_1  |     at QuerySet.then (/services/registry/node_modules/ormnomnom/lib/queryset.js:260:12)
registry_1  |     at QuerySet.get (/services/registry/node_modules/ormnomnom/lib/queryset.js:115:43)
registry_1  |     at DAO.proto.get (/services/registry/node_modules/ormnomnom/lib/ormnomnom.js:66:29)
registry_1  |     at oauthCallback (/services/registry/handlers/www.js:97:6)
registry_1  |     at processTicksAndRejections (internal/process/task_queues.js:89:5)
registry_1  |     at async inner (/services/common/boltzmann/middleware/dev-only.js:45:16)
registry_1  |     at async inner (/services/common/boltzmann/middleware/dev-only.js:45:16) {
registry_1  |   name: 'error',
registry_1  |   length: 105,
registry_1  |   severity: 'FATAL',
registry_1  |   code: '3D000',
redis_1     | 1:C 03 Jun 2019 21:
```

However, the .env file has `entropic_dev` as the database name and when I grep the code base for `entropic_development` there's nothing there.

However when i changed `NODE_ENV` to `dev` from the default of `development` everything was kosher.

I think this has something to do with:

```
registry_1  | > entropic-registry@0.0.1 migrate /services/registry
registry_1  | > PGUSER=postgres PGDATABASE=entropic_${NODE_ENV:-dev} db-migrate up --config db-migrate.json --env entropic
```

I'm gonna try to take a quick look at that tonight

**Comment by toddself** [comment]
Looks like #128 addresses this!

**Comment by gribnoysup** [comment]
I think it's would be nice to keep the issue open until PR lands for visibility purposes 👍 I'll add the "closes" thingie in the PR also
