### ISSUE TITLE
Cannot connect to Postgres db in docker-compose

### ISSUE THREAD

**Issue by olingern** [entropic-dev/entropic#190]
### Description
The registry started failing to connect to the postgres database on master sometime in the past day. 

Removing `prestart` inside of the registry's `package.json` fixes the issue, so I'm fairly certain that it's to do with the migration config. 

**Error:**
[ERROR] AssertionError [ERR_ASSERTION]: ifError got unwanted exception: connect ECONNREFUSED 127.0.0.1:5432

**Full `docker-compose up`**
```
[olingern@archtop entropic]$ docker-compose up
Starting entropic_db_1    ... done
Starting entropic_redis_1 ... done
Starting entropic_queue_1 ... done
Starting entropic_registry_1 ... done
Attaching to entropic_redis_1, entropic_queue_1, entropic_db_1, entropic_registry_1
redis_1     | 1:C 06 Jun 2019 23:16:15.280 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 1:C 06 Jun 2019 23:16:15.280 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1     | 1:C 06 Jun 2019 23:16:15.280 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1     | 1:M 06 Jun 2019 23:16:15.283 * Running mode=standalone, port=6379.
redis_1     | 1:M 06 Jun 2019 23:16:15.283 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1     | 1:M 06 Jun 2019 23:16:15.283 # Server initialized
redis_1     | 1:M 06 Jun 2019 23:16:15.283 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1     | 1:M 06 Jun 2019 23:16:15.283 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1     | 1:M 06 Jun 2019 23:16:15.283 * DB loaded from disk: 0.000 seconds
redis_1     | 1:M 06 Jun 2019 23:16:15.283 * Ready to accept connections
db_1        | 2019-06-06 23:16:15.495 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1        | 2019-06-06 23:16:15.495 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1        | 2019-06-06 23:16:15.499 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1        | 2019-06-06 23:16:15.519 UTC [18] LOG:  database system was shut down at 2019-06-06 14:50:34 UTC
db_1        | 2019-06-06 23:16:15.527 UTC [1] LOG:  database system is ready to accept connections
registry_1  | 
registry_1  | > entropic-registry@0.0.1 prestart /services/registry
registry_1  | > NODE_ENV=dev npm run createdb >/dev/null; NODE_ENV=dev npm run migrate
registry_1  | 
registry_1  | 
registry_1  | > entropic-registry@0.0.1 migrate /services/registry
registry_1  | > PGUSER=postgres PGDATABASE=entropic_${NODE_ENV:-dev} db-migrate up --config db-migrate.json --env entropic
registry_1  | 
registry_1  | [ERROR] AssertionError [ERR_ASSERTION]: ifError got unwanted exception: connect ECONNREFUSED 127.0.0.1:5432
registry_1  |     at module.exports (/services/registry/node_modules/db-migrate/lib/commands/helper/assert.js:9:14)
registry_1  |     at /services/registry/node_modules/db-migrate/lib/commands/up.js:19:14
registry_1  |     at /services/registry/node_modules/db-migrate/connect.js:17:7
registry_1  |     at /services/registry/node_modules/db-migrate/lib/driver/index.js:95:9
registry_1  |     at /services/registry/node_modules/db-migrate-pg/index.js:662:7
registry_1  |     at Connection.connectingErrorHandler (/services/registry/node_modules/db-migrate-pg/node_modules/pg/lib/client.js:163:14)
registry_1  |     at Connection.emit (events.js:200:13)
registry_1  |     at Socket.reportStreamError (/services/registry/node_modules/db-migrate-pg/node_modules/pg/lib/connection.js:71:10)
registry_1  |     at Socket.emit (events.js:200:13)
registry_1  |     at emitErrorNT (internal/streams/destroy.js:91:8)
registry_1  |     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
registry_1  |     at processTicksAndRejections (internal/process/task_queues.js:84:9)
registry_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
registry_1  | npm ERR! code ELIFECYCLE
registry_1  | npm ERR! errno 1
registry_1  | npm ERR! entropic-registry@0.0.1 migrate: `PGUSER=postgres PGDATABASE=entropic_${NODE_ENV:-dev} db-migrate up --config db-migrate.json --env entropic`
registry_1  | npm ERR! Exit status 1
registry_1  | npm ERR! 
registry_1  | npm ERR! Failed at the entropic-registry@0.0.1 migrate script.
registry_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
registry_1  | 
registry_1  | npm ERR! A complete log of this run can be found in:
registry_1  | npm ERR!     /root/.npm/_logs/2019-06-06T23_16_17_180Z-debug.log
registry_1  | npm ERR! code ELIFECYCLE
registry_1  | npm ERR! errno 1
registry_1  | npm ERR! entropic-registry@0.0.1 prestart: `NODE_ENV=dev npm run createdb >/dev/null; NODE_ENV=dev npm run migrate`
registry_1  | npm ERR! Exit status 1
registry_1  | npm ERR! 
registry_1  | npm ERR! Failed at the entropic-registry@0.0.1 prestart script.
registry_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
registry_1  | 
registry_1  | npm ERR! A complete log of this run can be found in:
registry_1  | npm ERR!     /root/.npm/_logs/2019-06-06T23_16_17_190Z-debug.log
entropic_registry_1 exited with code 1
```
### Steps to reproduce

- `docker-compose up`

### System Details

**OS**: Arch Linux x86_64
**docker**: 18.09.6-ce, build 481bc77156
**docker-compose**: 1.24.0

**Comment by zacanger** [comment]
Do you have anything in `.env` overriding the defaults? That `127.0.0.1` doesn't look right, and db-migrate should be using the host from `db-migrate.json`, which gets it from `$PGHOST`.

**Comment by olingern** [comment]
That's what I thought, too.

Here's my `.env`

```shell
NODE_ENV=development
DEV_LATENCY_ERROR_MS=10000
POSTGRES_URL=postgres://postgres@db:5432
POSTGRES_HOST=db
REDIS_URL=redis://redis:6379
PORT=3000
PGUSER=postgres
PGDATABASE=entropic_dev
CACHE_DIR=../data/entropic-cache
OAUTH_GITHUB_CLIENT=gh_client_id_here
OAUTH_GITHUB_SECRET=gh_secret_here
OAUTH_PASSWORD=pw_for_encrypting_tokens_here
EXTERNAL_HOST=http://localhost:3000
SESSION_SECRET=long_pw_for_encrypting_sessions_here
SESSION_EXPIRY_SECONDS=31536000

```

Here's the output of `docker network ls`. The `entropic_entropic` is interesting. I was attempting to start with a clean slate. It looked to me there was an orphaned network so I thought there might be some conflict there.

Steps to reproduce:
- `docker-compose up`
- `docker-compose down`
- `docker-compose network ls`
- `docker network rm $(docker network ls | grep "bridge" | awk '/ / { print $1 }')`
- `docker rm $(docker ps -qa --no-trunc --filter "status=exited")`
- `docker-compose up`

```terminal
[olingern@archtop registry]$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
7b8e3a7cb29d        bridge              bridge              local
28133b5ea708        entropic            bridge              local
e01e2c26bca3        entropic_default    bridge              local
90880dddbb97        host                host                local
64e811b7b7a9        none                null                local

[olingern@archtop registry]$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
7b8e3a7cb29d        bridge              bridge              local
4b2045308f27        entropic_entropic   bridge              local
90880dddbb97        host                host                local
64e811b7b7a9        none                null                local
```

**Comment by zacanger** [comment]
Ah, I think I see the issue. Your `.env` is a little out of date with master, there were some changes for consistency. The two lines you should change are:

```
NODE_ENV=dev
PGHOST=db
```

**Comment by olingern** [comment]
That's it! Ugh, totally overlooked that 5+ times. Thanks a ton! :bowing_man::bowing_man::bowing_man:
