### ISSUE TITLE
Some tests failing on master

### ISSUE THREAD

**Issue by olingern** [entropic-dev/entropic#192]
### Description

I noticed some tests are failing when running `npm test` from the root of the project.

```
invitations to namespaces
TypeError: Cannot read property 'warn' of undefined
    at /home/olingern/Code/entropic/services/registry/middleware/bearer-auth.js:44:24
    3) pass an extensive integration test

  invitations to packages
TypeError: Cannot read property 'warn' of undefined
    at /home/olingern/Code/entropic/services/registry/middleware/bearer-auth.js:44:24
    4) pass an extensive integration test


  10 passing (308ms)
  1 pending
  4 failing

  1) entropic
       must be a member of the namespace to create a package:

      AssertionError: 200 must be equivalent to 403
      + expected - actual

      -200
      +403
      
      at /home/olingern/Code/entropic/services/registry/test/01-packages.js:53:30
      at processTicksAndRejections (internal/process/task_queues.js:89:5)
      at async testHandler (test/utils/registry.js:21:7)
      at async Context.<anonymous> (test/utils/postgres.js:36:7)

  2) entropic
       can create packages in its own namespace:

      AssertionError: 200 must be equivalent to 201
      + expected - actual

      -200
      +201
      
      at /home/olingern/Code/entropic/services/registry/test/01-packages.js:80:30
      at processTicksAndRejections (internal/process/task_queues.js:89:5)
      at async testHandler (test/utils/registry.js:21:7)
      at async Context.<anonymous> (test/utils/postgres.js:36:7)

  3) invitations to namespaces
       pass an extensive integration test:
     FetchError: invalid json response body at http://localhost:38779/v1/namespaces/namespace/gryffindor@localhost:3000/members/potter reason: Unexpected end of JSON input
      at /home/olingern/Code/entropic/services/registry/node_modules/node-fetch/lib/index.js:272:32
      at processTicksAndRejections (internal/process/task_queues.js:89:5)
      at async /home/olingern/Code/entropic/services/registry/test/03-invitations.js:46:20
      at async testHandler (test/utils/registry.js:21:7)
      at async Context.<anonymous> (test/utils/postgres.js:36:7)

  4) invitations to packages
       pass an extensive integration test:

      AssertionError: 200 must be equivalent to 201
      + expected - actual

      -200
      +201
      
      at /home/olingern/Code/entropic/services/registry/test/03-invitations.js:177:30
      at processTicksAndRejections (internal/process/task_queues.js:89:5)
      at async testHandler (test/utils/registry.js:21:7)
      at async Context.<anonymous> (test/utils/postgres.js:36:7)
```
### Steps to reproduce
- Navigate to project root
- Run `npm test`

### System Details

**OS**: Arch Linux x86_64
**docker**: 18.09.6-ce, build 481bc77156
**docker-compose**: 1.24.0

**Comment by zacanger** [comment]
The tests are currently set up to run in Docker (to run in CI). If you're already inside the docker network, they pass, or if you have the postgres running locally. It should be possible to script running them in Docker locally.
