### ISSUE TITLE
Authentication not found

### ISSUE THREAD

**Issue by olingern** [entropic-dev/entropic#202]
### Description
Retrieving authentication objects during login is currently throwing an error. Currently the error is [not logged](https://github.com/entropic-dev/entropic/blob/master/services/registry/handlers/www.js#L96).

```
  const authn = await Authentication.objects
    .get({
      active: true,
      remote_identity: remote.id,
      provider: provider.name,
      'user.active': true
    })
    .catch(e => {
      console.log("====== ERROR =====")
     console.log(e)});
```

**My logs:**

```
stry_1  | 2019-06-07T17:00:54.348Z  info req: 172.18.0.1 200 GET /www/login 404 23ms
registry_1  | ====== URL 
registry_1  | 0.8944597594055097
registry_1  | ====== client state
registry_1  | 0.8944597594055097
registry_1  | ====== REMOTE =======
registry_1  | { id: 'olingern', username: 'olingern', email: 'olingern@gmail.com' }
registry_1  | ========= authentication ---------
registry_1  | NotFound [Error]: Authentication not found
registry_1  |     at /services/registry/node_modules/ormnomnom/lib/queryset.js:118:17
registry_1  |     at tryCatcher (/services/registry/node_modules/bluebird/js/release/util.js:16:23)
registry_1  |     at Promise._settlePromiseFromHandler (/services/registry/node_modules/bluebird/js/release/promise.js:512:31)
registry_1  |     at Promise._settlePromise (/services/registry/node_modules/bluebird/js/release/promise.js:569:18)
registry_1  |     at Promise._settlePromise0 (/services/registry/node_modules/bluebird/js/release/promise.js:614:10)
registry_1  |     at Promise._settlePromises (/services/registry/node_modules/bluebird/js/release/promise.js:694:18)
registry_1  |     at _drainQueueStep (/services/registry/node_modules/bluebird/js/release/async.js:138:12)
registry_1  |     at _drainQueue (/services/registry/node_modules/bluebird/js/release/async.js:131:9)
registry_1  |     at Async._drainQueues (/services/registry/node_modules/bluebird/js/release/async.js:147:5)
registry_1  |     at Immediate.Async.drainQueues [as _onImmediate] (/services/registry/node_modules/bluebird/js/release/async.js:17:14)
registry_1  |     at processImmediate (internal/timers.js:439:21) {
registry_1  |   type: 'authentication'
registry_1  | }

```
### How to reproduce
- `docker-compose up`
- navigate to http://localhost:3000/www/login
- attempt to login

**Comment by chrisdickinson** [comment]
(#135 will change how this works pretty drastically, as a heads up!)

**Comment by olingern** [comment]
Gotcha! I'll keep this open in case someone else runs into it, but looking forward to #135 :tada:

**Comment by olingern** [comment]
I think this is good to close!
