### ISSUE TITLE
ds login  or ds --version 

### ISSUE THREAD

**Issue by moogacs** [entropic-dev/entropic#241]
# Is this a feature request or a bug?
Bug
# Expected behavior:
redirect to github to login 
# Actual behavior:
Error: /Users/$USRNAME/.entropicrc
    at load (/usr/local/lib/node_modules/ds/lib/config.js:21:11)
# Steps to replicate:

# Environment info (where relevant)
- Browser:
- Operating System & Version:
OSX 10.14.5
- Version of Node (`node -v`):
v12.4.0
- Version of ds (`ds --version`):
error
    at load (/usr/local/lib/node_modules/ds/lib/config.js:21:11)

**Comment by moogacs** [comment]
It's still related to #104 for even node v12

**Comment by zacanger** [comment]
https://github.com/entropic-dev/entropic/blob/master/cli/lib/config.js#L21 if you're up to date with master, that error would seem to imply that you have a syntax error in your `~/.entropicrc`. It should look something like

```toml
[registries."https://registry.entropic.dev"]
token = "ent_v1_TOKEN_HERE"
```

Could you post the contents here (with token redacted)?

**Comment by moogacs** [comment]
That's is the point actually , I am up to date with master but the point is  ~/.entropicrc not theres at all not created

**Comment by moogacs** [comment]
it trying to load non existing file and dir (the error make sense), the point is where is actual .entropicrc creation

**Comment by zacanger** [comment]
The file gets created by [this function](https://github.com/entropic-dev/entropic/blob/master/cli/lib/config.js#L34) which is called [here](https://github.com/entropic-dev/entropic/blob/master/cli/lib/commands/login.js#L32). Could you add a `console.log(e)` before the `throw` [here](https://github.com/entropic-dev/entropic/blob/master/cli/lib/config.js#L20) and see if there are any more details?

**Comment by moogacs** [comment]
that what i expected and then after logging 


[Error: EISDIR: illegal operation on a directory, read] {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}

**Comment by zacanger** [comment]
Ah okay, so that's saying you have a directory at `~/.entropicrc`, and it's trying to use `readFile.

**Comment by moogacs** [comment]
cool it's working now, but suppose that we provide an error for that case !

**Comment by moogacs** [comment]
what about changing [this](https://github.com/entropic-dev/entropic/blob/master/cli/lib/config.js#L17)  with if (e.code === 'ENOENT' || e.code === 'EISDIR') {

**Comment by zacanger** [comment]
That would still wind up throwing an error in the `save` function. It might make sense to just add another case, something like:


```javascript
if (e.code === 'ENOENT') {
  return {};
}

if (e.code === 'EISDIR') {
  throw new errors.CouldNotReadConfigFile(filename, 'File is a directory!');
}

throw new errors.CouldNotReadConfigFile(filename, e);
```

**Comment by moogacs** [comment]
@zacanger if you wouldn't mind i will have a PR for it

**Comment by viktor-ku** [comment]
https://github.com/entropic-dev/entropic/pull/186

This will make lifes easier since it's handling everything in sync. Also modified error messages.
